version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admintask
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: tasks
    ports:
      - "5499:5432"